import { WooCommerceProduct } from "@/lib/woocommerce-types";

// --- DUMMY DATA SETUP (sin usar funciones) ---

const MOCK_DATE = "2025-10-25T14:00:00";
const MOCK_DATE_GMT = "2025-10-25T17:00:00";

// Generador de Slugs simple para la coherencia de los datos mock
const generateSlug = (name: string) =>
  name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

// URLs base de permalink
const PERMALINK_BASE = "https://trendify-store.com/product/";
const API_BASE = "https://trendify-store.com/wp-json/wc/v3/products/";

// --- MOCK DE PRODUCTOS COMPLETOS ---

export const mockProducts: WooCommerceProduct[] = [
  // Producto 1: Premium Wireless Headphones
  {
    id: 1,
    name: "Premium Wireless Headphones",
    slug: generateSlug("Premium Wireless Headphones"),
    permalink: PERMALINK_BASE + generateSlug("Premium Wireless Headphones"),
    date_created: MOCK_DATE,
    date_created_gmt: MOCK_DATE_GMT,
    date_modified: MOCK_DATE,
    date_modified_gmt: MOCK_DATE_GMT,
    type: "simple",
    status: "publish",
    featured: true,
    catalog_visibility: "visible",
    description:
      "High-quality wireless headphones with noise cancellation and premium sound quality.",
    short_description:
      "Experimenta la excelencia en audio inalámbrico con cancelación de ruido activa.",
    sku: "ELEC-HPH-001",
    price: "199.99",
    regular_price: "199.99",
    sale_price: "",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: false,
    purchasable: true,
    total_sales: 85,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: 0,
    download_expiry: 0,
    external_url: "",
    button_text: "",
    tax_status: "taxable",
    tax_class: "",
    manage_stock: true,
    stock_quantity: 120,
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: 15,
    sold_individually: false,
    weight: "0.5",
    dimensions: { length: "15", width: "10", height: "22" },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: "electronica-media",
    shipping_class_id: 10,
    reviews_allowed: true,
    average_rating: "4.8",
    rating_count: 45,
    upsell_ids: [3, 7],
    cross_sell_ids: [7],
    parent_id: 0,
    purchase_note: "Gracias por tu compra de auriculares de alta gama.",
    categories: [{ id: 10, name: "Electronics", slug: "electronics" }],
    brands: [{ id: 1, name: "SoundWave", slug: "soundwave" }],
    tags: [{ id: 101, name: "Wireless", slug: "wireless" }],
    images: [
      {
        id: 1001,
        date_created: MOCK_DATE,
        date_created_gmt: MOCK_DATE_GMT,
        date_modified: MOCK_DATE,
        date_modified_gmt: MOCK_DATE_GMT,
        src: "https://ik.imagekit.io/p2ho5d9bi/Trendify/premium-wireless-headphones.png?updatedAt=1758028871437",
        name: "Premium Wireless Headphones",
        alt: "Premium Wireless Headphones",
        srcset: "",
        sizes: "",
        thumbnail: "", // Valores dummy para campos adicionales
      },
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    price_html:
      '<span class="woocommerce-Price-amount amount">199,99&nbsp;<span class="woocommerce-Price-currencySymbol">€</span></span>',
    related_ids: [3, 7],
    meta_data: [],
    stock_status: "instock",
    has_options: false,
    post_password: "",
    global_unique_id: "gid://woocommerce/Product/1",
    _links: {
      self: [{ href: API_BASE + "1" }],
      collection: [{ href: API_BASE }],
    },
  },

  // Producto 2: Organic Cotton T-Shirt
  {
    id: 2,
    name: "Organic Cotton T-Shirt",
    slug: generateSlug("Organic Cotton T-Shirt"),
    permalink: PERMALINK_BASE + generateSlug("Organic Cotton T-Shirt"),
    date_created: MOCK_DATE,
    date_created_gmt: MOCK_DATE_GMT,
    date_modified: MOCK_DATE,
    date_modified_gmt: MOCK_DATE_GMT,
    type: "variable",
    status: "publish",
    featured: false,
    catalog_visibility: "visible",
    description:
      "Comfortable and sustainable organic cotton t-shirt available in multiple colors.",
    short_description: "Camiseta de algodón orgánico, suave y ecológica.",
    sku: "CLT-TSH-002",
    price: "29.99",
    regular_price: "29.99",
    sale_price: "",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: false,
    purchasable: true,
    total_sales: 210,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: 0,
    download_expiry: 0,
    external_url: "",
    button_text: "Seleccionar Opciones",
    tax_status: "taxable",
    tax_class: "standard",
    manage_stock: true,
    stock_quantity: 350,
    backorders: "notify",
    backorders_allowed: true,
    backordered: false,
    low_stock_amount: 50,
    sold_individually: false,
    weight: "0.2",
    dimensions: { length: "30", width: "20", height: "3" },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: "ropa-ligera",
    shipping_class_id: 12,
    reviews_allowed: true,
    average_rating: "4.5",
    rating_count: 90,
    upsell_ids: [],
    cross_sell_ids: [6],
    parent_id: 0,
    purchase_note: "Disfruta de la comodidad del algodón orgánico.",
    categories: [{ id: 20, name: "Clothing", slug: "clothing" }],
    brands: [{ id: 2, name: "EcoWear", slug: "ecowear" }],
    tags: [{ id: 102, name: "Organic", slug: "organic" }],
    images: [
      {
        id: 2002,
        date_created: MOCK_DATE,
        date_created_gmt: MOCK_DATE_GMT,
        date_modified: MOCK_DATE,
        date_modified_gmt: MOCK_DATE_GMT,
        src: "https://ik.imagekit.io/p2ho5d9bi/Trendify/organic-cotton-t-shirt.jpg?updatedAt=1758028869135",
        name: "organic cotton t-shirt",
        alt: "organic cotton t-shirt",
        srcset: "",
        sizes: "",
        thumbnail: "",
      },
    ],
    attributes: [{ id: 1, name: "Color", option: ["Red", "Blue", "Green"] }],
    default_attributes: [{ id: 1, name: "Color", option: "Blue" }],
    variations: [21, 22, 23],
    grouped_products: [],
    menu_order: 0,
    price_html:
      '<span class="woocommerce-Price-amount amount">29,99&nbsp;<span class="woocommerce-Price-currencySymbol">€</span></span>',
    related_ids: [6, 8],
    meta_data: [],
    stock_status: "instock",
    has_options: true,
    post_password: "",
    global_unique_id: "gid://woocommerce/Product/2",
    _links: {
      self: [{ href: API_BASE + "2" }],
      collection: [{ href: API_BASE }],
    },
  },

  // Producto 3: Smart Fitness Watch
  {
    id: 3,
    name: "Smart Fitness Watch",
    slug: generateSlug("Smart Fitness Watch"),
    permalink: PERMALINK_BASE + generateSlug("Smart Fitness Watch"),
    date_created: MOCK_DATE,
    date_created_gmt: MOCK_DATE_GMT,
    date_modified: MOCK_DATE,
    date_modified_gmt: MOCK_DATE_GMT,
    type: "simple",
    status: "publish",
    featured: true,
    catalog_visibility: "visible",
    description:
      "Advanced fitness tracking with heart rate monitoring, GPS, and smartphone integration.",
    short_description: "Reloj inteligente para monitoreo de actividad y salud.",
    sku: "ELEC-SMT-003",
    price: "159.99",
    regular_price: "199.99",
    sale_price: "159.99",
    date_on_sale_from: MOCK_DATE,
    date_on_sale_from_gmt: MOCK_DATE_GMT,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: true,
    purchasable: true,
    total_sales: 110,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: 0,
    download_expiry: 0,
    external_url: "",
    button_text: "Comprar Ahora",
    tax_status: "taxable",
    tax_class: "",
    manage_stock: true,
    stock_quantity: 80,
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: 10,
    sold_individually: false,
    weight: "0.1",
    dimensions: { length: "10", width: "10", height: "5" },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: "electronica-pequena",
    shipping_class_id: 11,
    reviews_allowed: true,
    average_rating: "4.9",
    rating_count: 65,
    upsell_ids: [1],
    cross_sell_ids: [7],
    parent_id: 0,
    purchase_note: "Empieza a monitorizar tu vida con el Smart Watch.",
    categories: [{ id: 10, name: "Electronics", slug: "electronics" }],
    brands: [{ id: 3, name: "FitPro", slug: "fitpro" }],
    tags: [{ id: 103, name: "Sale", slug: "sale" }],
    images: [
      {
        id: 3003,
        date_created: MOCK_DATE,
        date_created_gmt: MOCK_DATE_GMT,
        date_modified: MOCK_DATE,
        date_modified_gmt: MOCK_DATE_GMT,
        src: "https://ik.imagekit.io/p2ho5d9bi/Trendify/smart-fitness-watch.png?updatedAt=1758028869547",
        name: "Smart Fitness Watch",
        alt: "Smart Fitness Watch",
        srcset: "",
        sizes: "",
        thumbnail: "",
      },
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 1,
    price_html:
      '<del><span class="woocommerce-Price-amount amount">199,99&nbsp;<span class="woocommerce-Price-currencySymbol">€</span></span></del> <ins><span class="woocommerce-Price-amount amount">159,99&nbsp;<span class="woocommerce-Price-currencySymbol">€</span></span></ins>',
    related_ids: [1, 7],
    meta_data: [],
    stock_status: "instock",
    has_options: false,
    post_password: "",
    global_unique_id: "gid://woocommerce/Product/3",
    _links: {
      self: [{ href: API_BASE + "3" }],
      collection: [{ href: API_BASE }],
    },
  },

  // Producto 4: Artisan Coffee Beans
  {
    id: 4,
    name: "Artisan Coffee Beans",
    slug: generateSlug("Artisan Coffee Beans"),
    permalink: PERMALINK_BASE + generateSlug("Artisan Coffee Beans"),
    date_created: MOCK_DATE,
    date_created_gmt: MOCK_DATE_GMT,
    date_modified: MOCK_DATE,
    date_modified_gmt: MOCK_DATE_GMT,
    type: "simple",
    status: "publish",
    featured: true,
    catalog_visibility: "visible",
    description:
      "Premium single-origin coffee beans roasted to perfection for the ultimate coffee experience.",
    short_description: "Granos de café de origen único, tueste artesanal.",
    sku: "FBV-CFB-004",
    price: "24.99",
    regular_price: "24.99",
    sale_price: "",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: false,
    purchasable: true,
    total_sales: 320,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: 0,
    download_expiry: 0,
    external_url: "",
    button_text: "Añadir al Carrito",
    tax_status: "taxable",
    tax_class: "",
    manage_stock: true,
    stock_quantity: 450,
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: 30,
    sold_individually: false,
    weight: "1.0",
    dimensions: { length: "20", width: "12", height: "6" },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: "alimentacion",
    shipping_class_id: 13,
    reviews_allowed: true,
    average_rating: "4.7",
    rating_count: 150,
    upsell_ids: [6],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: "¡Disfruta de tu café!",
    categories: [
      { id: 30, name: "Food and Beverage", slug: "food-and-beverage" },
    ],
    brands: [{ id: 4, name: "The Roastery", slug: "the-roastery" }],
    tags: [{ id: 104, name: "Artisan", slug: "artisan" }],
    images: [
      {
        id: 4004,
        date_created: MOCK_DATE,
        date_created_gmt: MOCK_DATE_GMT,
        date_modified: MOCK_DATE,
        date_modified_gmt: MOCK_DATE_GMT,
        src: "https://ik.imagekit.io/p2ho5d9bi/Trendify/artisan-coffee-beans.jpg?updatedAt=1758028865675",
        name: "coffee beans roasted",
        alt: "coffee beans roasted",
        srcset: "",
        sizes: "",
        thumbnail: "",
      },
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    price_html:
      '<span class="woocommerce-Price-amount amount">24,99&nbsp;<span class="woocommerce-Price-currencySymbol">€</span></span>',
    related_ids: [6],
    meta_data: [],
    stock_status: "instock",
    has_options: false,
    post_password: "",
    global_unique_id: "gid://woocommerce/Product/4",
    _links: {
      self: [{ href: API_BASE + "4" }],
      collection: [{ href: API_BASE }],
    },
  },

  // Producto 5: Minimalist Desk Lamp
  {
    id: 5,
    name: "Minimalist Desk Lamp",
    slug: generateSlug("Minimalist Desk Lamp"),
    permalink: PERMALINK_BASE + generateSlug("Minimalist Desk Lamp"),
    date_created: MOCK_DATE,
    date_created_gmt: MOCK_DATE_GMT,
    date_modified: MOCK_DATE,
    date_modified_gmt: MOCK_DATE_GMT,
    type: "simple",
    status: "publish",
    featured: true,
    catalog_visibility: "visible",
    description:
      "Modern LED desk lamp with adjustable brightness and sleek minimalist design.",
    short_description: "Lámpara de escritorio LED con diseño moderno.",
    sku: "HMO-LMP-005",
    price: "89.99",
    regular_price: "89.99",
    sale_price: "",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: false,
    purchasable: true,
    total_sales: 65,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: 0,
    download_expiry: 0,
    external_url: "",
    button_text: "Añadir al Carrito",
    tax_status: "taxable",
    tax_class: "",
    manage_stock: true,
    stock_quantity: 95,
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: 10,
    sold_individually: false,
    weight: "1.2",
    dimensions: { length: "40", width: "15", height: "45" },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: "decoracion",
    shipping_class_id: 14,
    reviews_allowed: true,
    average_rating: "4.6",
    rating_count: 35,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: "Ilumina tu espacio de trabajo.",
    categories: [{ id: 40, name: "Food and Office", slug: "food-and-office" }], // Manteniendo el nombre de categoría original
    brands: [{ id: 5, name: "LumiDesk", slug: "lumidesk" }],
    tags: [{ id: 105, name: "LED", slug: "led" }],
    images: [
      {
        id: 5005,
        date_created: MOCK_DATE,
        date_created_gmt: MOCK_DATE_GMT,
        date_modified: MOCK_DATE,
        date_modified_gmt: MOCK_DATE_GMT,
        src: "https://ik.imagekit.io/p2ho5d9bi/Trendify/minimalist-desk-lamp.png?updatedAt=1758028868739",
        name: "LED desk lamp",
        alt: "LED desk lamp",
        srcset: "",
        sizes: "",
        thumbnail: "",
      },
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    price_html:
      '<span class="woocommerce-Price-amount amount">89,99&nbsp;<span class="woocommerce-Price-currencySymbol">€</span></span>',
    related_ids: [4],
    meta_data: [],
    stock_status: "instock",
    has_options: false,
    post_password: "",
    global_unique_id: "gid://woocommerce/Product/5",
    _links: {
      self: [{ href: API_BASE + "5" }],
      collection: [{ href: API_BASE }],
    },
  },

  // Producto 6: Eco-Friendly Water Bottle
  {
    id: 6,
    name: "Eco-Friendly Water Bottle",
    slug: generateSlug("Eco-Friendly Water Bottle"),
    permalink: PERMALINK_BASE + generateSlug("Eco-Friendly Water Bottle"),
    date_created: MOCK_DATE,
    date_created_gmt: MOCK_DATE_GMT,
    date_modified: MOCK_DATE,
    date_modified_gmt: MOCK_DATE_GMT,
    type: "simple",
    status: "publish",
    featured: true, // Asumido de 'featured: { categories: { name: "Food and Beverage" } }'
    catalog_visibility: "visible",
    description:
      "Sustainable stainless steel water bottle that keeps drinks cold for 24 hours.",
    short_description: "Botella reutilizable de acero inoxidable, 500ml.",
    sku: "LFS-WTR-006",
    price: "34.99",
    regular_price: "34.99",
    sale_price: "",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: false,
    purchasable: true,
    total_sales: 150,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: 0,
    download_expiry: 0,
    external_url: "",
    button_text: "Añadir al Carrito",
    tax_status: "taxable",
    tax_class: "",
    manage_stock: true,
    stock_quantity: 250,
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: 25,
    sold_individually: false,
    weight: "0.4",
    dimensions: { length: "8", width: "8", height: "28" },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: "general",
    shipping_class_id: 15,
    reviews_allowed: true,
    average_rating: "4.9",
    rating_count: 80,
    upsell_ids: [4],
    cross_sell_ids: [2],
    parent_id: 0,
    purchase_note: "Mantente hidratado de forma sostenible.",
    categories: [{ id: 50, name: "Lifestyle", slug: "lifestyle" }], // Mapeo de la antigua propiedad 'category'
    brands: [{ id: 6, name: "AquaPure", slug: "aquapure" }],
    tags: [{ id: 106, name: "Eco", slug: "eco" }],
    images: [
      {
        id: 6006,
        date_created: MOCK_DATE,
        date_created_gmt: MOCK_DATE_GMT,
        date_modified: MOCK_DATE,
        date_modified_gmt: MOCK_DATE_GMT,
        src: "https://ik.imagekit.io/p2ho5d9bi/Trendify/eco-friendly-water-bottle.png?updatedAt=1758028868886", // Mapeo de 'image_url'
        name: "Eco-Friendly Water Bottle",
        alt: "Eco-Friendly Water Bottle",
        srcset: "",
        sizes: "",
        thumbnail: "",
      },
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    price_html:
      '<span class="woocommerce-Price-amount amount">34,99&nbsp;<span class="woocommerce-Price-currencySymbol">€</span></span>',
    related_ids: [4, 2],
    meta_data: [],
    stock_status: "instock",
    has_options: false,
    post_password: "",
    global_unique_id: "gid://woocommerce/Product/6",
    _links: {
      self: [{ href: API_BASE + "6" }],
      collection: [{ href: API_BASE }],
    },
  },

  // Producto 7: Wireless Charging Pad
  {
    id: 7,
    name: "Wireless Charging Pad",
    slug: generateSlug("Wireless Charging Pad"),
    permalink: PERMALINK_BASE + generateSlug("Wireless Charging Pad"),
    date_created: MOCK_DATE,
    date_created_gmt: MOCK_DATE_GMT,
    date_modified: MOCK_DATE,
    date_modified_gmt: MOCK_DATE_GMT,
    type: "simple",
    status: "publish",
    featured: false, // Mapeo del booleano 'featured'
    catalog_visibility: "visible",
    description:
      "Fast wireless charging pad compatible with all Qi-enabled devices.",
    short_description: "Base de carga inalámbrica rápida.",
    sku: "ELEC-CHG-007",
    price: "49.99",
    regular_price: "49.99",
    sale_price: "",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: false,
    purchasable: true,
    total_sales: 90,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: 0,
    download_expiry: 0,
    external_url: "",
    button_text: "Añadir al Carrito",
    tax_status: "taxable",
    tax_class: "",
    manage_stock: true,
    stock_quantity: 150,
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: 15,
    sold_individually: false,
    weight: "0.25",
    dimensions: { length: "12", width: "12", height: "1" },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: "electronica-pequena",
    shipping_class_id: 11,
    reviews_allowed: true,
    average_rating: "4.4",
    rating_count: 50,
    upsell_ids: [1],
    cross_sell_ids: [3],
    parent_id: 0,
    purchase_note: "Carga sin cables, sin complicaciones.",
    categories: [{ id: 10, name: "Electronics", slug: "electronics" }],
    brands: [{ id: 1, name: "SoundWave", slug: "soundwave" }],
    tags: [{ id: 101, name: "Wireless", slug: "wireless" }],
    images: [
      {
        id: 7007,
        date_created: MOCK_DATE,
        date_created_gmt: MOCK_DATE_GMT,
        date_modified: MOCK_DATE,
        date_modified_gmt: MOCK_DATE_GMT,
        src: "https://ik.imagekit.io/p2ho5d9bi/Trendify/wireless-charging-pad.png?updatedAt=1758028869942",
        name: "Wireless Charging Pad",
        alt: "Wireless Charging Pad",
        srcset: "",
        sizes: "",
        thumbnail: "",
      },
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    price_html:
      '<span class="woocommerce-Price-amount amount">49,99&nbsp;<span class="woocommerce-Price-currencySymbol">€</span></span>',
    related_ids: [1, 3],
    meta_data: [],
    stock_status: "instock",
    has_options: false,
    post_password: "",
    global_unique_id: "gid://woocommerce/Product/7",
    _links: {
      self: [{ href: API_BASE + "7" }],
      collection: [{ href: API_BASE }],
    },
  },

  // Producto 8: Luxury Skincare Set
  {
    id: 8,
    name: "Luxury Skincare Set",
    slug: generateSlug("Luxury Skincare Set"),
    permalink: PERMALINK_BASE + generateSlug("Luxury Skincare Set"),
    date_created: MOCK_DATE,
    date_created_gmt: MOCK_DATE_GMT,
    date_modified: MOCK_DATE,
    date_modified_gmt: MOCK_DATE_GMT,
    type: "simple",
    status: "publish",
    featured: true, // Mapeo del booleano 'featured'
    catalog_visibility: "visible",
    description:
      "Complete skincare routine with natural ingredients for healthy, glowing skin.",
    short_description:
      "Rutina completa de cuidado de la piel con ingredientes naturales.",
    sku: "BTY-SET-008",
    price: "129.99",
    regular_price: "129.99",
    sale_price: "",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: false,
    purchasable: true,
    total_sales: 55,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: 0,
    download_expiry: 0,
    external_url: "",
    button_text: "Añadir al Carrito",
    tax_status: "taxable",
    tax_class: "reduced-rate",
    manage_stock: true,
    stock_quantity: 70,
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: 5,
    sold_individually: false,
    weight: "0.9",
    dimensions: { length: "25", width: "20", height: "10" },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: "belleza",
    shipping_class_id: 16,
    reviews_allowed: true,
    average_rating: "5.0",
    rating_count: 30,
    upsell_ids: [2],
    cross_sell_ids: [6],
    parent_id: 0,
    purchase_note: "Mima tu piel con este set de lujo.",
    categories: [{ id: 60, name: "Beauty", slug: "beauty" }],
    brands: [{ id: 7, name: "NaturaLux", slug: "naturalux" }],
    tags: [{ id: 107, name: "Luxury", slug: "luxury" }],
    images: [
      {
        id: 8008,
        date_created: MOCK_DATE,
        date_created_gmt: MOCK_DATE_GMT,
        date_modified: MOCK_DATE,
        date_modified_gmt: MOCK_DATE_GMT,
        src: "https://ik.imagekit.io/p2ho5d9bi/Trendify/luxury-skincare-set.png?updatedAt=1758028869820",
        name: "Luxury Skincare Set",
        alt: "Luxury Skincare Set",
        srcset: "",
        sizes: "",
        thumbnail: "",
      },
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    price_html:
      '<span class="woocommerce-Price-amount amount">129,99&nbsp;<span class="woocommerce-Price-currencySymbol">€</span></span>',
    related_ids: [2, 6],
    meta_data: [],
    stock_status: "instock",
    has_options: false,
    post_password: "",
    global_unique_id: "gid://woocommerce/Product/8",
    _links: {
      self: [{ href: API_BASE + "8" }],
      collection: [{ href: API_BASE }],
    },
  },
];
